### ISSUE TITLE
Decouple up2date dps and ddi implementation

### ISSUE THREAD

**Issue by jenisov** [rtsoft-sdc/up2date-cpp#1]
Split implementation into two (three) modules: _DDI i_mplementation, _DPS_ implementation and _common_ glue.

- DDI client must just take mTLS key-pair to authorize Hawkbit.

- In case mTLS pair is not accepted an update hook must tell DPS to refresh.

- DDI api also takes hawkbit endpoint and (?) controller ID (**if X509 keypair doesn't already contain this metadata**).

- TLS keypair storage must be injected externally to DDI client (i.e. DDI client must not care where keypair is located)

Unit tests must be implemented:

- DDI client with pre-provisioned keypair
- DPS client standalone

**Comment by aleksandrovrts** [comment]
@jenisov, Unit tests will be implemented in #7
