### ISSUE TITLE
Provide a safe way to stop the client

### ISSUE THREAD

**Issue by vchaplinski** [rtsoft-sdc/up2date-cpp#24]
Summary
----------
Currently there's no way to leave the infinite blocking loop implemented in HawkbitCommunicationClient::Run method.
This is needed, for instance, in order to restart client when communication settings have changed (e.g. with new Cerftificate, hawkbit Uri etc,). This feature would also be useful to enable smooth client deactivation during agent software upgrade/removal.

Suggestion is to add Stop method to Client interface and implement it in HawkbitCommunicationClient.
This method shall be non-blocking and thread-safe.
It shall guarantee exitting from Run method in reasonable time (matter of a few seconds at max).

Drawbacks
------------
This feature may sunstantially complicate Run method implementation.

**Comment by aleksandrovrts** [comment]
Example usage (based on examples/basic_handler.hpp):
We can use raw pointer bcs Handler methods are called in Client context. Client will be released by smart ptr.  
```
class Handler : public EventHandler {
    Client *client{};
public:

    void setClient(Client *client_) {
        client = client_;
    }
    ...
```   

Then when creating the Client:

```
auto builder = DDIClientBuilder::newInstance();     
auto handler = std::make_shared<Handler>();      
auto client = ...     
    ->build();     
handler->setClient(client.get());  
client->run();
``` 
  
Then in any actions in Handler class just call 
```
this->client->stop();
```

Service will stop polling when action handling in finished.   
PS. I think it is better to call stop in *ResponseDeliveryListener* classes.

**Comment by aleksandrovrts** [comment]
https://github.com/rtsoft-gmbh/up2date-cpp/commit/55eeaa7bd5686b9575f3a70967c9ce83e3cbbea3
