### ISSUE TITLE
Response::Execution enum doesn't have DOWNLOAD and DOWNLOADED values

### ISSUE THREAD

**Issue by vchaplinski** [rtsoft-sdc/up2date-cpp#32]
Add support for DOWNLOAD and DOWNLOADED values of the Response::Execution enum.
See https://www.eclipse.org/hawkbit/apis/ddi_api/

**Comment by aleksandrovrts** [comment]
Givven docs is outdated.
Implement from src: https://github.com/eclipse/hawkbit/blob/3d3481110e5131958d8c2d3292b438eed77332c4/hawkbit-rest/hawkbit-ddi-api/src/main/java/org/eclipse/hawkbit/ddi/json/model/DdiStatus.java#L121
